[package]
#REPLACE project-name project-name
name = "project-name"
version = "0.1.0"
edition = "2021"

[dependencies]
esp-backtrace = { version = "0.14.1", features = [
    #REPLACE esp32c6 mcu
    "esp32c6",
    "exception-handler",
    "panic-handler",
    #IF option("probe-rs")
    #+"defmt",
    #ELSE
    "println",
    #ENDIF
]}

esp-hal = { version = "0.20.1", features = [
    #REPLACE esp32c6 mcu
    "esp32c6",
    #IF option("probe-rs")
    #+"defmt",
    #ENDIF
] }
#IF !option("probe-rs")
#REPLACE esp32c6 mcu
esp-println = { version = "0.11.0", features = ["esp32c6", "log"] }
log = { version = "0.4.21" }
#ENDIF
#IF option("alloc")
esp-alloc = { version = "0.4.0" }
#ENDIF
#IF option("wifi")
embedded-io = "0.6.1"
esp-wifi = { version = "0.9.1", default-features=false, features = [
    #REPLACE esp32c6 mcu
    "esp32c6",
    "phy-enable-usb",
    "utils",
    "wifi",
    "esp-alloc",
    #IF option("probe-rs")
    #+"defmt",
    #ENDIF
    #IF !option("probe-rs")
    "log",
    #ENDIF
] }
heapless = { version = "0.8.0", default-features = false }
smoltcp = { version = "0.11.0", default-features = false, features = [
    "medium-ethernet",
    "proto-dhcpv4",
    "proto-igmp",
    "proto-ipv4",
    "socket-dhcpv4",
    "socket-icmp",
    "socket-raw",
    "socket-tcp",
    "socket-udp",
] }
#ENDIF
#IF option("ble")
#+ embedded-io = "0.6.1"
#+ esp-wifi = { version = "0.9.1", default-features=false, features = [
#REPLACE esp32c6 mcu
#+     "esp32c6",
#+     "phy-enable-usb",
#+     "ble",
#+     "esp-alloc",
#IF option("probe-rs")
#+     #+"defmt",
#ENDIF
#IF !option("probe-rs")
#+     "log",
#ENDIF
#+ ] }
#+ heapless = { version = "0.8.0", default-features = false }
#+ bleps = { git = "https://github.com/bjoernQ/bleps", package = "bleps", rev = "a5148d8ae679e021b78f53fd33afb8bb35d0b62e", features = [ "macros", "async"] }
#ENDIF
#IF option("probe-rs")
#+defmt            = "0.3.8"
#+defmt-rtt        = "0.4.1"
#ENDIF
embassy-executor = { version = "0.6.0",  features = [
    #IF option("probe-rs")
    "defmt"
    #ENDIF
] }
embassy-time     = { version = "0.3.1",  features = ["generic-queue-8"] }
#REPLACE esp32c6 mcu
esp-hal-embassy  = { version = "0.3.0",  features = ["esp32c6"] }
static_cell      = { version = "2.1.0",  features = ["nightly"] }

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units = 1        # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false

[patch.crates-io]
esp-hal = { git = "https://github.com/esp-rs/esp-hal.git", rev = "be82a6521a5859129ca4f98e54e4d4d6cedffe76"}
esp-wifi = { git = "https://github.com/esp-rs/esp-hal.git", rev = "be82a6521a5859129ca4f98e54e4d4d6cedffe76"}
esp-hal-embassy = { git = "https://github.com/esp-rs/esp-hal.git", rev = "be82a6521a5859129ca4f98e54e4d4d6cedffe76"}
esp-alloc = { git = "https://github.com/esp-rs/esp-hal.git", rev = "be82a6521a5859129ca4f98e54e4d4d6cedffe76"}
