#INCLUDEFILE option("cargo-embed")
[default.probe]
protocol = "Jtag"

[default.general]
#REPLACE esp32c6 mcu
chip = "esp32c6"

[default.rtt]
enabled = true
#IF option("defmt")
up_channels = [
    { channel = 0, format = "Defmt" },
]
#ENDIF
